Task5
PavelKevor/formal_languages pull request #10
Opened 2020-12-23 03:02 UTC by PavelKevor

5 задание.

2020-12-25 06:51 UTC, gsvgit requested changes
Добавьте, пожалуйста, тестов.

2020-12-25 06:51 UTC, gsvgit commented on src/tests.py
> +    graph.read_triples("tests/graph_test5.txt")
Количество тесов, конечно поражает. Можно хоть как-то разнообразить? Всякими крайними случаями, например. Чуть более интересными граммтиками и графами.

2021-01-22 15:26 UTC, PavelKevor commented
Добавил тесты

2021-01-29 07:08 UTC, gsvgit approved these changes
Ок.

2021-12-05 17:55 UTC, merged